// Code generated by MockGen. DO NOT EDIT.
// Source: main.go

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	ssm "github.com/aws/aws-sdk-go-v2/service/ssm"
	gomock "github.com/golang/mock/gomock"
)

// MockssmClient is a mock of ssmClient interface.
type MockssmClient struct {
	ctrl     *gomock.Controller
	recorder *MockssmClientMockRecorder
}

// MockssmClientMockRecorder is the mock recorder for MockssmClient.
type MockssmClientMockRecorder struct {
	mock *MockssmClient
}

// NewMockssmClient creates a new mock instance.
func NewMockssmClient(ctrl *gomock.Controller) *MockssmClient {
	mock := &MockssmClient{ctrl: ctrl}
	mock.recorder = &MockssmClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockssmClient) EXPECT() *MockssmClientMockRecorder {
	return m.recorder
}

// GetParameter mocks base method.
func (m *MockssmClient) GetParameter(ctx context.Context, params *ssm.GetParameterInput, optFns ...func(*ssm.Options)) (*ssm.GetParameterOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetParameter", varargs...)
	ret0, _ := ret[0].(*ssm.GetParameterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParameter indicates an expected call of GetParameter.
func (mr *MockssmClientMockRecorder) GetParameter(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParameter", reflect.TypeOf((*MockssmClient)(nil).GetParameter), varargs...)
}
